// Code generated by ent, DO NOT EDIT.

package booking

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the booking type in the database.
	Label = "booking"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldInformation holds the string denoting the information field in the database.
	FieldInformation = "information"
	// FieldStartHour holds the string denoting the start_hour field in the database.
	FieldStartHour = "start_hour"
	// FieldEndHour holds the string denoting the end_hour field in the database.
	FieldEndHour = "end_hour"
	// FieldBookingDate holds the string denoting the booking_date field in the database.
	FieldBookingDate = "booking_date"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeRoom holds the string denoting the room edge name in mutations.
	EdgeRoom = "room"
	// Table holds the table name of the booking in the database.
	Table = "bookings"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "bookings"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_bookings"
	// RoomTable is the table that holds the room relation/edge.
	RoomTable = "bookings"
	// RoomInverseTable is the table name for the Room entity.
	// It exists in this package in order to avoid circular dependency with the "room" package.
	RoomInverseTable = "rooms"
	// RoomColumn is the table column denoting the room relation/edge.
	RoomColumn = "room_bookings"
)

// Columns holds all SQL columns for booking fields.
var Columns = []string{
	FieldID,
	FieldInformation,
	FieldStartHour,
	FieldEndHour,
	FieldBookingDate,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "bookings"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"room_bookings",
	"user_bookings",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultBookingDate holds the default value on creation for the "booking_date" field.
	DefaultBookingDate time.Time
)

// OrderOption defines the ordering options for the Booking queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByInformation orders the results by the information field.
func ByInformation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInformation, opts...).ToFunc()
}

// ByStartHour orders the results by the start_hour field.
func ByStartHour(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartHour, opts...).ToFunc()
}

// ByEndHour orders the results by the end_hour field.
func ByEndHour(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndHour, opts...).ToFunc()
}

// ByBookingDate orders the results by the booking_date field.
func ByBookingDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBookingDate, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByRoomField orders the results by room field.
func ByRoomField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRoomStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newRoomStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RoomInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, RoomTable, RoomColumn),
	)
}
