package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.48

import (
	"context"
	"fmt"
	"room-reservation/ent"
	graphql1 "room-reservation/graphql"
)

// User is the resolver for the user field.
func (r *bookingResolver) User(ctx context.Context, obj *ent.Booking) (*ent.User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// Room is the resolver for the room field.
func (r *bookingResolver) Room(ctx context.Context, obj *ent.Booking) (*ent.Room, error) {
	panic(fmt.Errorf("not implemented: Room - room"))
}

// Booking returns graphql1.BookingResolver implementation.
func (r *Resolver) Booking() graphql1.BookingResolver { return &bookingResolver{r} }

type bookingResolver struct{ *Resolver }
