package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.48

import (
	"context"
	"fmt"
	"room-reservation/ent"
	graphql1 "room-reservation/graphql"
)

// CreateBooking is the resolver for the createBooking field.
func (r *mutationResolver) CreateBooking(ctx context.Context, input ent.CreateBookingInput) (*ent.Booking, error) {
	panic(fmt.Errorf("not implemented: CreateBooking - createBooking"))
}

// UpdateBooking is the resolver for the updateBooking field.
func (r *mutationResolver) UpdateBooking(ctx context.Context, id string, input ent.UpdateBookingInput) (*ent.Booking, error) {
	panic(fmt.Errorf("not implemented: UpdateBooking - updateBooking"))
}

// DeleteBooking is the resolver for the deleteBooking field.
func (r *mutationResolver) DeleteBooking(ctx context.Context, id string) (*ent.Booking, error) {
	panic(fmt.Errorf("not implemented: DeleteBooking - deleteBooking"))
}

// Mutation returns graphql1.MutationResolver implementation.
func (r *Resolver) Mutation() graphql1.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
