package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.48

import (
	"context"
	"fmt"
	"room-reservation/ent"
	graphql1 "room-reservation/graphql"
	"time"
)

// GetRoom is the resolver for the GetRoom field.
func (r *queryResolver) GetRoom(ctx context.Context, id string) (*ent.Room, error) {
	panic(fmt.Errorf("not implemented: GetRoom - GetRoom"))
}

// GetAllRooms is the resolver for the GetAllRooms field.
func (r *queryResolver) GetAllRooms(ctx context.Context) ([]*ent.Room, error) {
	panic(fmt.Errorf("not implemented: GetAllRooms - GetAllRooms"))
}

// BookingsByDate is the resolver for the bookingsByDate field.
func (r *queryResolver) BookingsByDate(ctx context.Context, date time.Time) ([]*ent.Booking, error) {
	panic(fmt.Errorf("not implemented: BookingsByDate - bookingsByDate"))
}

// BookingsByRoomAndDate is the resolver for the bookingsByRoomAndDate field.
func (r *queryResolver) BookingsByRoomAndDate(ctx context.Context, roomID string, date time.Time) ([]*ent.Booking, error) {
	panic(fmt.Errorf("not implemented: BookingsByRoomAndDate - bookingsByRoomAndDate"))
}

// Query returns graphql1.QueryResolver implementation.
func (r *Resolver) Query() graphql1.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
