// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package ent

import (
	"time"
)

type AuthenticationToken struct {
	AccessToken  string    `json:"accessToken"`
	RefreshToken string    `json:"refreshToken"`
	TokenType    string    `json:"tokenType"`
	ExpiresAt    time.Time `json:"expiresAt"`
	Email        string    `json:"email"`
}

type CreateBookingInput struct {
	Information string     `json:"information"`
	StartHour   time.Time  `json:"startHour"`
	EndHour     time.Time  `json:"endHour"`
	BookingDate *time.Time `json:"bookingDate,omitempty"`
	UserID      string     `json:"userID"`
	RoomID      string     `json:"roomID"`
}

type UpdateBookingInput struct {
	Information *string    `json:"information,omitempty"`
	StartHour   *time.Time `json:"startHour,omitempty"`
	EndHour     *time.Time `json:"endHour,omitempty"`
	BookingDate *time.Time `json:"bookingDate,omitempty"`
	UserID      *string    `json:"userID,omitempty"`
	RoomID      *string    `json:"roomID,omitempty"`
}
